### ISSUE TITLE
update~ play

### ISSUE THREAD

**Issue by porres** [porres/pd-cyclone#141]
add secondary outlet (ban when finished)

about @loop / @loopinterp & @interptime

so, when you enable "interpolation around the start and end points for a loop" with @loopinterp [int], you "interpolate" with a "crossfade"...

@loopinterp only happens if you have the loop on - set with the @loop attrinbute

the default crossfad time for @loopinterp is 50ms, but you can change it with @interptime [float]

So... you have a loop section into the file! Say it's 5 seconds long, but you loop from 1 sec to 3 seconds... then, what it does at the loop point, is that it "fades in" starting from 1 second, but it will fade out from 3 seconds and on as long as the interptime, for a maximum of 2 seconds.

**Comment by derekxkwan** [comment]
is this a linear crossfade? meaning, the gain of loop 1 is g, the fading in one is 1-g? 

also in our example,.. loop is 1 -3 seconds,.. let's say loop 1 is the one fading in,.. so at sec 1,.. g = 0? and this goes for the 50 ms  = .05 s, so by sec 1.05, g is at 1 and loop 2 would've faded out since 1-g = 0 at that point. and then at 3 seconds, g starts declining again right? so from 3 to 3.05 seconds, g for loop 1 goes from 1 to 0 and 1-g (for loop 2) goes from 0 to 1, starting wtih the samples at sec 1. so in effect the loop is actually 1 to 3.05 seconds (ie, loopstart to loopend + xfade). What if say,.. your sample is 5 seconds long,.. and your loop is from 3 to 5 seconds? theres' no extra bit at the end to allow the xfading. so i suppose the only valid values for loopend go up to (end of sample - xfade)?

**Comment by derekxkwan** [comment]
also i dunno what the extra outlet play~ has does, as noted in my pull for cybuffing =)

**Comment by porres** [comment]
I'm yet to test if it's linear, but seems like it

and yes, your cross fade can't meaningly go over the end sample range. It's my idea that the end of a sample fades out anyway. So say I have a file 5 sec long and I do loop it to start at 2 seconds (range 2-5) with a crossfade of 2.5 seconds long. All we hear is the file fading in till 4.5 seconds and then dying away, in a loop...

2nd outlet is bang when reaching end of play
