### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by porres** [porres/pd-cyclone#175]

**Comment by derekxkwan** [comment]
i think it's been gpl v2 in the past? i'd have to double check. so I suppose the real issue is whether to upgrade to gpl v3 or stick with v2. Not an expert on it all, but I know Linus Torvalds doesn't like gpl v3 for its limiting the use of DRM with gpl v3 licensed software, not sure if that really affects us here,.. there's a discussion on stack overflow here http://stackoverflow.com/questions/41460/what-are-the-differences-between-gpl-v2-and-gpl-v3-licenses .  i dunno if we'd have the right to change it to something lesser like BSD, we'd have to contact all the original maintainers i suppose... Anyways, I'm borrowed from some codebases that are GPL v2 at least (like iemguts) so I don't think that gives us much choice in the matter anyways...

**Comment by porres** [comment]
this is what we inherited https://github.com/porres/pd-cyclone/blob/master/LICENSE.txt

**Comment by porres** [comment]
let's just keep it BSD
