### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by porres** [porres/pd-cyclone#317]
**To do For "Cyclone 0.3 beta-3" Release (planned for february 21st 2018):**

High priority:

- [zl] group issue https://github.com/porres/pd-cyclone/issues/380
- [table] https://github.com/porres/pd-cyclone/issues/368

---------------

**Cycle 0.3 Beta 4 Release:**

- [zl]: add  sort method from max 4 & iter issue: https://github.com/porres/pd-cyclone/issues/107

- [sprintf]: check issues and add missing types: https://github.com/porres/pd-cyclone/issues/349 

- Finish 

- [mousestate] https://github.com/porres/pd-cyclone/issues/351

- Finish fixing objects already updated/partially fixed: 
       - [record~] https://github.com/porres/pd-cyclone/issues/170 
       - [buffir~] https://github.com/porres/pd-cyclone/issues/339
       - [coll]: https://github.com/porres/pd-cyclone/issues/211  (basically just deal with filetype and get it over with) 

- Fix an updated but not yet fixed object: [vectral~]: https://github.com/porres/pd-cyclone/issues/355 

- Check out this issue with [zerox~]: https://github.com/porres/pd-cyclone/issues/298

---------------

**Cycle 0.3 Beta 5 Release:**

- Remaining objects that need to be updated: 
       - [zl]: add missing methods (13 methods from Max 5: change, compare, delace, lace, lookup, median, queue, scramble, stack, stream, sum, thin and unique / 2 from Max 7: indexmap, swap)
       - [comment]: https://github.com/porres/pd-cyclone/issues/277 
       - [seq]: add support for "Type 1" MIDI Files, and => https://github.com/porres/pd-cyclone/issues/258 

- Object Resizing bug: https://github.com/porres/pd-cyclone/issues/223

---------------

**Cyclone 0.3 Final Release:**

- Finish new objects not quite finished yet => biquad~ (?) / cascade~ / filtercoeff~ / freqshift~ / hilbert~ / phaseshift~

**==> Revise documentation, add meta**

**==> Check double precision in filters, phase, etc**

**==> Think about "symbol" output:**

since max considers all symbol atoms as a "symbol message", maybe we should consider all symbolic atoms as symbols instead of "anything" when they're coming out of cyclone's objects...

some pd objects do that by the way, such as "unpack"

**==> Non Cyclone fixes:**

- 9 objects not working in purr data: https://git.purrdata.net/jwilkes/purr-data/issues/355

- Fix nbx for vanilla, so [number~] works fine: - it is not printing 'nans' and  'nan' / 'inf' are printed in a weird way on windows

**==> Reorganising:**

- why do we need these things on the makefile for magic or shared???

cflags = -Ishared -DHAVE_STRUCT_TIMESPEC

uname := $(shell uname -s)

- deal with shared: https://github.com/porres/pd-cyclone/issues/381

- remove hloud

- have an audio folder for cybuf in shared, move magicbits to common

- or maybe just have one simple folder with dependencies

- try to get rid at least of loud altogether

- remove fitter from scope~ ?

- Empty trash

**Comment by derekxkwan** [comment]
so we want to copy over the given wavetable to a specific [cycle~] instance? or have somehow global [cycle~] tables bound to symbols? what benefits/differences are there for copying over tables? besides possibly still having access to a table if you delete the array.

**Comment by porres** [comment]
not going much for festures, but just keeping it as it was and how it the behaviour is in max. In this way, you can change the array/wavetable and not interfere with the object. I guess you could change the wavetable how you like and then tell it to load it so changes take effect or something. Why, do you think this is bad?

**Comment by derekxkwan** [comment]
Overhead concerns I suppose being one of them, namely say if you have 1000 of them, like if they're in an abstraction and you load that abstraction via [clone]  (but then I suppose perhaps wavetables shouldn't be that long anyays? but what if they are). I suppose it should be a per-instance thing since instroducing a whole new namespace of symbols for cycle would get confusing as heck.

 So then I suppose that passing the symbol argt for cycle~ should refer to the array as is, so if you have an array "susie" (say, of white noise) and you have [cycle~ susie], it copies susie into its own table, but then you fill susie with I dunno, a with a sinesum, then susie's contents have changed, [cycle~ susie] did not, which is what you're saying.

that situation could get a little confusing if we added a new [cycle~ susie] and since susie is now a bunch of sines, this new [cycle~ susie] would be a bunch of sines, despite looking exactly like the old [cycle~ susie], which has white noise in it bc that's what susie had when we instantiated that one.

**Comment by porres** [comment]
well, I don't really get it but it seems we need to think this through then, or that is not an easy thing to just revert back and do? I don't know... but if it is any complicated we can move it out of the "short term" things and just deal with stuff we can get out of the way quickly ;)

**Comment by porres** [comment]
how about the record~ issue?

**Comment by derekxkwan** [comment]
do you mean actual array size or loopstart and end?

if we're talking about actual array size, the problem is that it's recording into the array proper that you pass. that is, if there's [array define bob], and [record~ bob], you're recording into bob directly, you're not recording locally and copying it over, so if your new array size is smaller than loopend, that's no good and you're trying to record into array that isn't there. i suppose mb then you could implement a safeguard and not write into the array if it goes past the array size but have sync pretend it's still actually recording? 

might not have time to address this for a while, but there are thoughts =P

**Comment by porres** [comment]
ok, will have to think more about that too when I have the time - also busy here ;)

is there anything else you could quickly act on?

**Comment by porres** [comment]
let's do this :)

**Comment by porres** [comment]
rebooting this
