### ISSUE TITLE
sending "bang" to funnel

### ISSUE THREAD

**Issue by LGoodacre** [porres/pd-cyclone#323]
If you send a "bang" message to the [funnel] object, it is supposed to output the last value (ie. "bang" to the 2nd inlet should give "2 3", if the inlet last received a 3).

This fails if the inlet hasn't received any input before the bang. Ie., creating a new funnel object and sending a "bang" to any inlet will print "bang". This is inconsistent with older versions of Cyclone, where a "bang" would give the correct output even if the toggle hadn't received any previous float.

**Comment by porres** [comment]
Hi, this was a bit confusing to me, but I checked things and now presume that what you say is that funnel should output "0" if it hadn't received anything instead of "bang".

This is in fact a new bug we may have introduced, because we did work on the bang method for funnel.

seems like an easy fix, expect it on the next release

thanks

**Comment by porres** [comment]
by the way, what we fixed in the bang method for funnel is that it was only working for number inputs and nothing else

**Comment by derekxkwan** [comment]
should be fixed with this

https://github.com/porres/pd-cyclone/pull/324

**Comment by porres** [comment]
it was fixed ;)

**Comment by LGoodacre** [comment]
Thanks guys. Looking forward to this in the new release.

**Comment by porres** [comment]
well, we're waiting for jonathan to include the new cyclone in Purr Data, which is supposed to happen any time now, and then we'll release an update along side with it

**Comment by porres** [comment]
it's been released ;)
