### ISSUE TITLE
[scope~] not showing signal trace

### ISSUE THREAD

**Issue by katjav** [porres/pd-cyclone#463]
When a patch with [scope~] is loaded while dsp is on (also when the loading patch itself enables dsp), the object will not show a signal trace. This behavior can be tested with the help patch or probably any other containing [scope~]. Load the patch while dsp is off, then switch dsp on: [scope~] will show the signal trace. Leave dsp on and reload the patch: [scope~] won't show the trace.

OS: Linux (MX17)
Pd: 0.49.0
cyclone: 0.4 from deken

**Comment by porres** [comment]
I cannot replicate this issue in macOS (10.14.6) with cyclone 0.4 and Pd 0.50-2

but I found issues on the help file that I already solved. 

will keep investigating though

**Comment by porres** [comment]
I can replicate this issue in macOS (10.14.6) with cyclone 0.4 and Pd 0.50-2 but not EVERY TIME, and only when there's a loadbang in the patch that starts DSP... something is weird - will keep investigating though and come back when I have a better report or solution.

**Comment by porres** [comment]
I can confirm this is also happening not only for cyclone 0.4 but also back to cyclone 0.3 alpha 1 (dating almost 3 years ago), so this is something we introduced way early. I barely touched [scope~] and back in the day I couldn't if I wanted, so this is probably something done by Matt Barber.

I remember seeing something funny like this but couldn't find out why it would happen sometimes. Now this issue can give us a good idea where to look - thanks!

by the way, I can get scope~ to wake up and show the signal trace if I delete a number box and then do a control-z... 

hopefully this isn't too complicated. Anyway, time to look at the code.

**Comment by porres** [comment]
This is getting weirder and harder to replicate on macOS. I'm trying it now with the latest state in the repository (not that any significant change has been made to scope~) and using the last state of Pd (0.51). It just works! But trying the same thing (0.51 and current state of cyclone) in Linux does not, all you reported here really happens in Linux and maybe Linux only... 

I can also see how hiding the window and opening it again also makes the object wake up and show the signal trace.

**Comment by porres** [comment]
I think I found the bug. It is related to Matt Barber's work on using his magic to check out if we have signal connections. Scope will then set its drawing mode according to inlet connections.

When we load a patch with the DSP On, the _**scope_dsp**_ function gets the signal connections to check which mode it's on and calls the _**scope_setxymode**_ function to set the mode.

The thing is that  _**scope_setxymode**_ checks if the canvas is visible or not and it'll only do the redraw if it's visible. The problem is that when _**scope_dsp**_  is called when you load a patch with the DSP on, it will think the patch window is not visible yet, when it is - therefore it doesn't draw anything.

**Comment by porres** [comment]
somehow, this may not always happen in macOS, but seems to always happen in Linux

**Comment by porres** [comment]
if you retrigger the dsp function doing something like creating a new object, or if you make the window invisible then visible again, scope~ wakes up and starts working!

**Comment by porres** [comment]
There are 2 ways to trigger the object to draw the foreground. When the DSP is on it'll set the mode and if the patch is visible it draws. We've seen this doesn't happen when the object is loaded with the DSP on, because it isn't visible yet.

There's a second way to trigger the foreground drawing, which is when the GUI gets the message that it is visible. The problem is that the code uses a variable named "x_lastxymode" to check what drawing mode the object is in. This variable is only updated inside the scope_perform routine.

In macOS, for some reason, this variable gets updated in time (at least most of times), so we get to draw things correctly. But in linux it never does, so we have an uninitialized value of "0" that will not draw anything.

If you wait a little to retrigger the object to draw things in one of these two ways, then the variable has already been initialized and it'll just work.

Anyway, I found the code with x_xymode and x_lastxymode quite confusing - I have no idea why we need to work with both of them and specially in the way we have it now. Matt did this code, so I'll ask him.

Well, this seems like an easy fix, we just need to make sure x_lastxymode gets initialized in time. I'll try a non intrusive way to do this.

**Comment by porres** [comment]
so, I did try my fix and it worked, but I still think the code looks quite unnecessarily complicated and now I just made it a little bit more complicated. I think it's worth revising this code.

**Comment by katjav** [comment]
Testing scope~ at latest revision 0f82a354. The issue got worse, on Linux at least. The help patch for [scope~] makes Pd crash soon as dsp is turned on. However in a simple test where [scope~] inlet isn't connected to a signal outlet, Pd doesn't crash before I try to connect.

Will you reopen this issue or should I open a new?

**Comment by porres** [comment]
I don't think you need to reopen. I tested and it works fine, but for that you need to compile it with the latest vanilla's source (which is close to the next 0.51 release state), because now the m_imp.h function got updated to include a function we use in scope~ and other objects as part of Matt's magic. If you don't, Pd will crash indeed so it may seem it got screwed. I made this change to test things, I wanted to see if it works if I compile this way and opened on Pd 0.50, and it does.

**Comment by porres** [comment]
See if you can test it this way please. If we still have issues, we can reopen. BTW, this is the change I was talking about https://github.com/porres/pd-cyclone/issues/467

**Comment by katjav** [comment]
Aah I overlooked that cyclone 0.4 needs Pd 0.51 but now see it in your readme. Will come back later.

**Comment by porres** [comment]
Actually cyclone 0.4.1 ;) or the current state

It doesn't really need anything from 0.51 yet to run, just to compile, and I tested and it seems to work just fine in earlier versions. I do hope of more changes to get into the 0.51 release and depending on which, cyclone will better run in the next update.

**Comment by katjav** [comment]
So I built Pd (e3a78da), and bleeding edge cyclone (0f82a35) against it as per instructions. I can confirm that the crash doesn't happen now (running in above-mentioned Pd 0.50.2 from github and also with 0.49). Moreover, solving reported issue; [scope~] shows signal trace regardsless whether DSP was enabled during patch loading, and also regardless whether [scope~] is on top level window or in a GOP.
