### ISSUE TITLE
Support for Purr-Data

### ISSUE THREAD

**Issue by gilbertohasnofb** [porres/pd-cyclone#466]
With version 0.3 released, are there any plans to fully support Purr-Data?

**Comment by porres** [comment]
it's the other way around, you should ask Purr Data to support cyclone 0.3

**Comment by porres** [comment]
Please realize that Purr Data doesn't actually even fully support cyclone 0.2! One way or another, there's nothing really stopping Purr Data to include cyclone 0.3 - if the full support would be the reason, then it shouldn't include 0.2 as well... 

I've opened many issues and requests for Purr Data to include cyclone 0.3, and it's been about 2 years I've done that, so I'm also just waiting.

There are a few externals that needed to be ported because of the GUI transition they made (and this also affects more GUI externals from other libraries in Pd Extended). This is true for both cyclone 0.2 and 0.3 versions.

Moreover, Purr Data doesn't also support some new features from the latest Pd Vanilla versions that would be required to fully support cyclone 0.3

some issues for reference: 
- https://git.purrdata.net/jwilkes/purr-data/issues/355
- https://git.purrdata.net/jwilkes/purr-data/issues/460
- https://git.purrdata.net/jwilkes/purr-data/issues/408

cheers

**Comment by gilbertohasnofb** [comment]
Thanks for all the info, Alexandre, I opened an issue requesting this from the Purr Data side.
