### ISSUE TITLE
[counter] changing direction after 'set' message gives wrong output.

### ISSUE THREAD

**Issue by H-MLim** [porres/pd-cyclone#577]
![image](https://user-images.githubusercontent.com/68152553/136591862-f3c91753-ea5b-48ce-a095-17471520e311.png)
here's a question about cyclone/counter. when I set numbers > change the direction > and press the bang (so, in a short, [set 10( > [0(1)( > bang), the counter adds two from the set number (in this example, I intended to make start from 10, but it goes from 12) and I don't know what's the problem. It's OK when you already turned the direction, but for the first time to change it (for example, 1 > 0, or vice versa), the unknown two numbers are always added. am I missing something from here?
[test.zip](https://github.com/porres/pd-cyclone/files/7312930/test.zip)

**Comment by porres** [comment]
please upload the patch, it helps

**Comment by H-MLim** [comment]
oops, sorry. I uploaded on drive here:
https://drive.google.com/file/d/1OA_AN2MRGGlLpb_7SVSHBaedpegc54ad/view?usp=sharing

**Comment by porres** [comment]
Counters can be tricky... In order to fix this, we'd have to change the code a lot! I will mark this as a 'won't fix' and as a "known bug" because there are simple work arounds, like changing the direction BEFORE setting the number.

Now, the same bug exists in the original object in MAX and if you want a better, simpler and nicer counter object, try [else/count] :)
